// Barrel de componentes genéricos de UI.
// Permite: import { PageHeader, FormModal, DataTable } from '../../components/ui'
export { default as PageHeader } from './PageHeader'
export { default as FormModal } from './FormModal'
export { default as ConfirmModal } from './ConfirmModal'
export { default as DataTable } from './DataTable'
export type { Columna, Paginacion } from './DataTable'
export { default as FilterBar, SelectFiltro } from './FilterBar'
export { default as EstadoBadge } from './EstadoBadge'
export { default as LoadingState } from './LoadingState'
export { default as EmptyState } from './EmptyState'
export { default as RowActions } from './RowActions'
export type { AccionFila } from './RowActions'
export { default as MaterialAutocomplete } from './MaterialAutocomplete'
export { default as Pagination } from './Pagination'
export { default as NumericInput } from './NumericInput'
export { default as AlertaProyecto } from './AlertaProyecto'
